language: node_js
node_js:
  - "node"
  - "6"
  - "5"

before_script:
  - npm install mocha
  - npm install chai

env:
  - CXX=g++-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

