language: node_js
node_js:
  - "node"
  - "6"
  - "5"
  
env:
  - CXX=g++-5

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5

install:
  - node-gyp rebuild -j 8
