language: node_js
node_js:
  - "stable"
  - "6"

jdk: openjdk6
sudo: false

# Undo _JAVA_OPTIONS environment variable
before_script:
  - _JAVA_OPTIONS=

branches:
  only:
    - master

install:
  - npm uninstall typescript --no-save
  - npm install
