language: node_js
node_js:
  - "stable"
  - "6"
  - "5"

sudo: false

install:
  - npm uninstall typescript
  - npm uninstall tslint
  - npm install
  - npm update

cache:
  directories:
    - node_modules

